aliases:
  - "shop"
  - "axshop"
  - "sh"

formatting:
  enabled: true
  type: dot
  basic:
    '1000': K
    '1000000': M
    '1000000000': B
    '1000000000000': T

# Types

# dot = 1.000.000
# commas = 1,000,000
# basic = 1M

currencies:
  vault: "Vault"
  beasttoken: "BeastToken"
  playerpoints: "PlayerPoints"

disabled-worlds:
  - "world_nether"

main-menu:
  name: "&aAvailable Shops"
  size: 27
  categories:
    - blocks:
        material: "DIAMOND_BLOCK"
        name: "&2• &aBlocks &2•"
        lore:
          - ""
          - "&7Click to open the shop."
        slot: 0
    - items:
        material: "DIAMOND_SWORD"
        name: "&2• &aItems &2•"
        lore:
          - ""
          - "&7Click to open the shop."
        slot: 1

shops:
  - blocks:
      name: "&2• &aBlocks &2•"
      size: 27
      items:
        filler1:
          slot: "1-7;19-25;9&17"
          material: "BLACK_STAINED_GLASS_PANE"
          name: ""
          lore: []
        filler2:
          slot: "0&8&18&26"
          material: "ORANGE_STAINED_GLASS_PANE"
          name: ""
          lore: []
        diamond-block:
          material: "DIAMOND_BLOCK"
          name: "&eDiamond Block"
          slot: 10
          currency: "vault"
          prices:
            buy: 100
            sell: 50
          lore:
            - ""
            - "&eLeft click &8» &6&lBUY &8» $&6{buyPrice}&a$"
            - "&eRight click &8» &6&lSELL &8» &a$&6{sellPrice}&a$"
            - "&eShift + Right click &8» &6&lSELL ALL"
            - ""
            - "&eValuta: &6{currency}"
  - items:
      name: "&2• &aItems &2•"
      size: 27
      items:
        filler1:
          slot: "1-7;19-25;9&17"
          material: "BLACK_STAINED_GLASS_PANE"
          name: ""
          lore: [ ]
        filler2:
          slot: "0&8&18&26"
          material: "ORANGE_STAINED_GLASS_PANE"
          name: ""
          lore: [ ]
        diamond-sword:
          material: "DIAMOND_SWORD"
          name: "&eDiamond Sword"
          slot: 10
          currency: "vault"
          prices:
            buy: 100
            sell: 50
          lore:
            - ""
            - "&eLeft click &8» &6&lBUY &8» $&6{buyPrice}&a$"
            - "&eRight click &8» &6&lSELL &8» &a$&6{sellPrice}&a$"
            - "&eShift + Right click &8» &6&lSELL ALL"
            - ""
            - "&eValuta: &6{currency}"
        op:
          material: "EMERALD"
          name: "&eOP on server"
          slot: 11
          currency: "vault"
          prices:
            buy: 100
            sell: 50
          custom:
            - "op %player%"
          lore:
            - ""
            - "&eLeft click &8» &6&lBUY &8» $&6{buyPrice}&a$"
            - "&eRight click &8» &6&lSELL &8» &a$&6{sellPrice}&a$"
            - "&eShift + Right click &8» &6&lSELL ALL"
            - ""
            - "&eValuta: &6{currency}"